process.env.RUNTIME_NODE_MODULES='/Users/mac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from '/Users/mac/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='/Users/mac/Desktop/CallDine/architecture-presentation', build=root+'/.build', out=root+'/output';
const skill='/Users/mac/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
const font=resolvePresentationFont({fontFamily:'Arial'});
const c={bg:'#fff8ee',ink:'#34231d',muted:'#88766b',accent:'#c9502f',line:'#ead7c0',paper:'#fffdf8',soft:'#f6e7d4',green:'#4e8358',purple:'#805299',teal:'#00897b'};
const icons={};
for(const name of ['calldine','bedrock','textract','transcribe','polly','chime','sagemaker','cloudwatch','s3','secrets','fastapi']){icons[name]=await sharp(await fs.readFile(build+'/assets/'+name+'.svg')).resize(512,512,{fit:'contain'}).png().toBuffer();}
for(const name of ['aws','next']) icons[name]=await fs.readFile(build+'/assets/'+name+'.png');
const sources='Source: CallDine repository scanned 12 September 2026. AWS icons: https://aws.amazon.com/architecture/icons/ . AWS logo: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png . Next.js logo: https://assets.vercel.com/image/upload/v1662130559/nextjs/Icon_light_background.png . FastAPI icon: https://github.com/fastapi/fastapi/blob/master/docs/en/docs/img/icon-white.svg . CallDine logo: Frontend/components/ui/Logo.tsx. Brand colors: Frontend/app/globals.css.';
function txt(s,t,x,y,w,h,size=30,color=c.ink,bold=false){let a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=t;a.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return a;}
function rect(s,x,y,w,h,fill=c.paper,stroke=c.line,dashed=false){return s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill,line:{fill:stroke,width:2,style:dashed?'dashed':'solid'}});}
function img(s,key,x,y,w,h=w){s.images.add({blob:icons[key],contentType:'image/png',alt:key+' logo',fit:'contain',position:{left:x,top:y,width:w,height:h}});}
function base(p,title,sub,index){const s=p.slides.add();s.background.fill=c.bg;img(s,'calldine',60,40,52);txt(s,'CallDine',125,47,260,48,32,c.accent,true);txt(s,title,60,130,1760,90,58,c.ink,true);if(sub)txt(s,sub,63,224,1760,75,29,c.muted);txt(s,String(index).padStart(2,'0'),1790,1002,70,40,25,c.muted);return s;}
function edge(s,a,b,from='right',to='left',dashed=false,color=c.accent){return s.shapes.connect(a,b,{kind:'elbow',fromSide:from,toSide:to,line:{fill:color,width:3,style:dashed?'dashed':'solid'},tail:{type:'triangle',width:'med',length:'med'}});}
function node(s,{x,y,w=490,h=230,title,desc='',icon,num,fill=c.paper,stroke=c.line}){
 const box=rect(s,x,y,w,h,fill,stroke);
 if(num){
  txt(s,String(num).padStart(2,'0'),x+25,y+20,75,48,28,c.accent,true);
  if(icon){if(icon==='fastapi')rect(s,x+w/2-48,y+30,96,96,c.teal,c.teal);img(s,icon,x+w/2-48,y+30,96);}
  const label=txt(s,title,x+25,y+(icon?151:97),w-50,80,36,c.ink,true);label.text.style={typeface:font,fontSize:36,color:c.ink,bold:true,alignment:'center',autoFit:'none'};
  return box;
 }
 const compact=h<150, size=compact?25:30;
 let tx=x+23,tw=w-46;
 if(icon){const iz=compact?58:64;if(icon==='fastapi')rect(s,x+20,y+20,iz,iz,c.teal,c.teal);img(s,icon,x+20,y+20,iz);tx=x+99;tw=w-122;}
 txt(s,title,tx,y+22,tw,compact?55:76,size,c.ink,true);
 if(desc)txt(s,desc,x+23,y+(compact?71:110),w-46,Math.max(40,h-(compact?76:115)),compact?22:25,c.muted);
 return box;
}
let script=[];
function steps(p,title,sub,data,takeaway,notes,src,planned=false){let s=base(p,title,planned?'Planned feature':'',p.slides.items.length+1);const pos=[[60,345],[715,345],[1370,345],[1370,655],[715,655],[60,655]];let boxes=data.map((d,i)=>node(s,{x:pos[i][0],y:pos[i][1],w:490,h:235,title:d[0],desc:'',icon:d[2],num:i+1,stroke:planned?c.purple:c.line}));for(let i=0;i<boxes.length-1;i++){if(i===2)edge(s,boxes[i],boxes[i+1],'bottom','top',planned,planned?c.purple:c.accent);else if(i<2)edge(s,boxes[i],boxes[i+1],'right','left',planned,planned?c.purple:c.accent);else edge(s,boxes[i],boxes[i+1],'left','right',planned,planned?c.purple:c.accent);}
 if(planned)txt(s,'Planned: live training and inference are not connected.',60,937,1750,65,28,c.purple,true);s.speakerNotes.textFrame.setText(notes+'\n\nSource files: '+src+'\n'+sources);script.push({title,notes,steps:data.map(d=>({label:d[0],say:d[1]}))});return s;}
function overview(){const p=Presentation.create({slideSize:{width:1920,height:1080}});const s=base(p,'Complete system architecture','Application services coordinate AI, voice, restaurant data and knowledge retrieval.',1);img(s,'aws',1530,12,330,145);
 txt(s,'APPLICATION RUNTIME',60,299,690,42,24,c.accent,true);txt(s,'AWS MANAGED SERVICES',1320,292,540,42,24,c.accent,true);
 const ui=node(s,{x:60,y:350,w:275,h:215,title:'Browser',desc:'Customer + admin\nVoice and text',icon:'calldine'});
 const next=node(s,{x:385,y:350,w:290,h:215,title:'Next.js',desc:'Interface + API proxy\nLocal port 3000',icon:'next'});
 const api=node(s,{x:755,y:350,w:390,h:215,title:'FastAPI',desc:'Routes + service orchestration\nLocal port 8000',icon:'fastapi'});
 edge(s,ui,next);edge(s,next,api);
 const chat=node(s,{x:755,y:620,w:390,h:135,title:'Chat + business tools',desc:'Knowledge, voice, orders, bookings'});edge(s,api,chat,'bottom','top');
 const q=node(s,{x:385,y:620,w:290,h:135,title:'Qdrant in Docker',desc:'Knowledge vectors'});edge(s,chat,q,'left','right',false,c.teal);
 const repo=node(s,{x:755,y:800,w:390,h:130,title:'Repositories',desc:'SQLModel data access'});edge(s,chat,repo,'bottom','top');
 const db=node(s,{x:385,y:800,w:290,h:130,title:'SQLite',desc:'Operational records'});edge(s,repo,db,'left','right');
 const ch=node(s,{x:60,y:620,w:275,h:190,title:'Chime SDK',desc:'Browser meeting\nBackend creates session',icon:'chime'});edge(s,ui,ch,'bottom','top');
 const defs=[['bedrock','Bedrock','GPT-OSS reasoning + Titan embeddings'],['s3','Amazon S3','PDFs, menu images, call recordings'],['textract','Amazon Textract','PDF text extraction'],['transcribe','Amazon Transcribe','Uploaded speech turns to text'],['polly','Amazon Polly','Neural voice synthesis']];
 const aws=defs.map((d,i)=>node(s,{x:1320,y:345+i*119,w:540,h:105,title:d[1],icon:d[0]}));defs.forEach((d,i)=>txt(s,d[2],1419,407+i*119,419,37,20,c.muted));
 const bus=rect(s,1230,397,2,476,c.accent,c.accent);edge(s,api,bus,'right','left');aws.forEach(a=>edge(s,bus,a,'right','left'));
 img(s,'bedrock',60,975,48);txt(s,'Guardrails: optional',120,983,360,47,24,c.muted);
 img(s,'sagemaker',495,975,48);txt(s,'SageMaker: planned',555,983,360,47,24,c.purple);
 img(s,'cloudwatch',955,975,48);txt(s,'CloudWatch: helper only',1015,983,440,47,24,c.muted);
 img(s,'secrets',1480,975,48);txt(s,'Secrets: helper only',1540,983,340,47,24,c.muted);
 s.speakerNotes.textFrame.setText('The browser uses the Next.js interface and server API proxy. FastAPI coordinates chat, voice, knowledge, orders and reservations. Controlled services call Bedrock, S3, Textract, Transcribe and Polly through AWS clients. Knowledge search uses Qdrant, while repositories access SQLite. The browser connects to Chime separately and FastAPI creates the session. Guardrails are optional chat configuration. SageMaker remains planned. CloudWatch and Secrets Manager have client factories only. Solid lines represent source-code paths, not verified live AWS operation. AWS hosting is not established.\n'+sources);return p;}

const detailed=Presentation.create({slideSize:{width:1920,height:1080}});
{
let s=base(detailed,'AI restaurant assistant','Architecture and workflow walkthrough',1);img(s,'aws',1240,295,560,300);img(s,'calldine',60,340,175);txt(s,'CallDine',265,376,700,130,94,c.accent,true);txt(s,'Voice conversations\nRestaurant knowledge\nOrders and reservations',65,590,1050,215,43,c.ink);img(s,'next',1290,690,145);rect(s,1530,709,114,114,c.teal,c.teal);img(s,'fastapi',1530,709,114);txt(s,'Next.js',1305,850,230,50,30);txt(s,'FastAPI',1510,850,230,50,30);txt(s,'Source-based walkthrough. Forecasting is shown as planned.',65,953,1650,50,28,c.muted);let notes='CallDine helps restaurant customers use voice or text to ask questions, order food and reserve tables. The interface uses Next.js. FastAPI coordinates AWS AI services and the restaurant database. This walkthrough explains each stage and keeps the planned forecasting feature separate from working application code.';s.speakerNotes.textFrame.setText(notes+'\n'+sources);script.push({title:'CallDine AI restaurant assistant',notes});}
steps(detailed,'A customer request','The application keeps authentication, AI orchestration and database access in separate layers.',[
 ['Customer input','A text message or a completed voice transcript.','calldine'],['Next.js API proxy','Forward the request and session credentials.','next'],['FastAPI routes','Authenticate the user and call the service.','fastapi'],['Chat and tools','Load memory, call Bedrock and execute selected tools.','bedrock'],['Repositories','Read or save records through SQLModel.'],['Customer response','Return the answer through Next.js and save the conversation.']
],'Local application runtime with AWS service calls. AWS hosting is not established.',
'The browser sends requests to Next.js API handlers. These handlers forward the session token to FastAPI. Routes authenticate the request and services handle the work. Chat Service loads saved conversation history and calls Bedrock. Tool requests run in Python business services, which use repositories to access SQLite. Responses return through Next.js. Some chat answers stream tokens, while tool-assisted and voice answers return completed text.',
'Frontend/app/api/conversations/[id]/messages/stream/route.ts; backend/app/services/chat_service.py; backend/app/core/database.py');
steps(detailed,'Knowledge ingestion','A restaurant PDF becomes searchable knowledge for the assistant.',[
 ['Upload the PDF','Admin submits a document through Next.js and FastAPI.','next'],['Store in S3','Save the PDF under knowledge/ and record job metadata.','s3'],['Extract the text','FastAPI starts Textract, polls status and fetches all pages.','textract'],['Split into chunks','FastAPI creates 1,000-character chunks without overlap.','fastapi'],['Create embeddings','Titan Text Embeddings V2 returns normalized 1,024-D vectors.','bedrock'],['Index in Qdrant','FastAPI saves vectors, text and source metadata.']
],'FastAPI coordinates each step. Processing runs as an in-process background task.',
'The admin uploads a PDF. FastAPI stores it in S3 and creates knowledge and job records in SQLite. An in-process background task starts asynchronous Textract detection. FastAPI polls the job and retrieves all text pages. It joins the detected lines, splits the text into one-thousand-character chunks, invokes Titan embeddings through Bedrock, and saves vectors plus document metadata in Qdrant. Progress updates go to SQLite. There is no separate durable queue in this implementation.',
'backend/app/services/knowledge_service.py; backend/app/services/embedding_service.py; backend/app/api/routes_knowledge.py');
steps(detailed,'Knowledge retrieval','Example question: “What is the restaurant’s cancellation policy?”',[
 ['Customer question','Chat Service sends conversation context to Bedrock.','calldine'],['Select a tool','Bedrock requests search-knowledge. FastAPI dispatches it.','bedrock'],['Embed the query','Titan converts the search query into a vector.','bedrock'],['Search Qdrant','FastAPI queries cosine similarity and retrieves four chunks.'],['Return the evidence','FastAPI returns the chunks as a Bedrock tool result.','fastapi'],['Answer the customer','Bedrock uses the retrieved restaurant text in its answer.','bedrock']
],'This is custom RAG. Database and vector access stay under backend control.',
'The assistant can search the restaurant documents when it needs a policy or another restaurant fact. Bedrock chooses the knowledge-search tool. FastAPI embeds the query with Titan, searches Qdrant and returns the top four text chunks as tool results. Bedrock then uses that evidence to produce an answer. Bedrock does not connect directly to Qdrant, and this project does not use managed Bedrock Knowledge Bases.',
'backend/app/services/chat_tools.py; backend/app/services/knowledge_service.py; backend/app/services/embedding_service.py');
steps(detailed,'AI reasoning and tool execution','Bedrock selects an action. FastAPI executes the restaurant operation.',[
 ['Conversation memory','Save the customer message and load saved messages.'],['Planner request','Send history and eight tool descriptions through Converse.','bedrock'],['Controlled dispatch','Map tool names and inputs to Python service functions.','fastapi'],['Business validation','Check stock, prices, booking availability and draft state.'],['Tool results','Return structured results. Allow up to four tool rounds.','bedrock'],['Final answer','Return customer-facing text and save the assistant message.']
],'Optional Guardrails attach to chat requests when the guardrail ID and version are set.',
'The chat model is GPT-OSS 20B on Bedrock. The planner receives conversation history and eight tools. FastAPI dispatches tool selections to knowledge, menu, order or reservation services. Tool results return to Bedrock for the answer or a further tool round. The code allows up to four execution rounds. Guardrails are optional request configuration on chat calls. Their actual AWS policy configuration was not verified. Titan embedding calls do not use this chat guardrail helper.',
'backend/app/services/chat_service.py; backend/app/services/chat_tools.py');
{
let s=base(detailed,'The eight business tools','Tool arguments describe the request. Services validate the operation.',detailed.slides.items.length+1);
const rows=[['search-knowledge','Retrieve four relevant restaurant document chunks.'],['search-menu','Read menu names, prices, availability and stock.'],['check-order-items','Validate requested items and calculate the subtotal.'],['create-order-draft','Save a draft after the delivery address confirmation flag.'],['confirm-order','Recheck stock and confirm the customer’s draft.'],['check-table-availability','Check table capacity and overlapping bookings.'],['create-reservation-draft','Save the collected booking details as a draft.'],['confirm-reservation','Recheck availability, assign a table and confirm.']];
rows.forEach((r,i)=>{let y=330+i* seventy();txt(s,r[0],65,y,650,48,30,c.accent,true);});function seventy(){return 73;}
let notes='There are eight tools. Knowledge and menu search retrieve current information. Order tools validate items, create a delivery draft and confirm it. Reservation tools check availability, create a draft and assign a table when confirming. The language model chooses tool arguments, while the service code performs business checks. The separate prototype MCP adapter exposes similar tools but is not the path used by the main Bedrock chat service.';s.speakerNotes.textFrame.setText(notes+'\nSource: backend/app/services/chat_tools.py; backend/app/mcp/server.py\n'+sources);script.push({title:'The eight business tools',notes,steps:rows.map(r=>({label:r[0],say:r[1]}))});}
steps(detailed,'Voice input and transcription','The browser uploads a completed utterance. Transcribe uses its streaming API on the backend.',[
 ['Create the session','FastAPI creates a Chime meeting, attendee and conversation.','chime'],['Capture microphone','Browser joins Chime and separately captures local PCM audio.'],['Detect a turn ending','About 1.8 seconds of silence ends the recorded utterance.'],['Upload the PCM turn','Next.js forwards the completed audio blob to FastAPI.','next'],['Transcribe the speech','FastAPI sends PCM chunks to Transcribe Streaming.','transcribe'],['Submit the transcript','Browser posts the returned text to Chat Service.','fastapi']
],'Chime is a separate meeting connection. No Chime-to-Transcribe bridge appears in this code.',
'FastAPI creates the Chime session and a voice conversation. The browser joins the meeting with the Chime SDK, but it also captures microphone audio locally for the assistant. After roughly one point eight seconds of silence, the browser uploads the completed PCM utterance. FastAPI reads it and sends chunks through the Transcribe Streaming client. The final transcript returns to the browser, which submits it to the chat endpoint. This is turn-based input, not a continuous microphone stream to the backend.',
'Frontend/components/voice/VoiceAssistant.tsx; backend/app/services/voice_service.py');
steps(detailed,'AI response and speech playback','The same conversation and business tools serve both voice and text.',[
 ['Reason and act','Chat Service uses Bedrock and the restaurant tools.','bedrock'],['Clean the answer','Remove formatting, emojis and internal identifiers.','fastapi'],['Request speech','Browser posts the completed answer to the speech endpoint.','next'],['Synthesize with Polly','FastAPI selects the configured neural voice and MP3 format.','polly'],['Play the response','MP3 bytes return through the app to the browser speaker.'],['Resume listening','Listen again after playback, or end a confirmed transaction.']
],'Turn-based conversation. The current flow does not support interrupting the assistant.',
'The transcript follows the same chat and tool process as a text message. Voice responses are cleaned into natural speech. The browser posts the completed answer to the speech endpoint. FastAPI invokes Polly with the configured neural voice, then yields MP3 bytes back through the application. Browser playback streams the audio when supported, with a blob fallback. Listening resumes after playback. The frontend can end the call after detecting an order or reservation confirmation in the answer.',
'backend/app/services/chat_service.py; backend/app/services/voice_service.py; Frontend/components/voice/VoiceAssistant.tsx');
steps(detailed,'Call recording and conversation history','Audio files and structured conversation records use different storage paths.',[
 ['Mix both sides','Web Audio combines the microphone with assistant playback.'],['Record the call','MediaRecorder collects one WebM recording in the browser.'],['Upload recording','Next.js forwards the file to FastAPI when the call ends.','next'],['Store audio in S3','Save audios/calls/{conversation.id}.webm.','s3'],['Save the reference','SQLite keeps the audio key and conversation messages.'],['Admin playback','FastAPI reads S3 audio and supports byte-range requests.','fastapi']
],'S3 stores the media. SQLite stores messages, metadata and the recording reference.',
'The browser mixes microphone input and the assistant’s played audio using Web Audio. MediaRecorder captures the mixed stream in WebM format. On call completion, the recording uploads through Next.js and FastAPI to S3. The conversation row stores the S3 key. Text messages remain in SQLite. When an admin plays the recording, FastAPI serves the stored audio and supports range reads for playback.',
'Frontend/components/voice/VoiceAssistant.tsx; backend/app/services/voice_service.py');
steps(detailed,'Delivery order confirmation','The customer reviews the address and order summary before confirmation.',[
 ['Find and validate','Search menu. Validate quantities, stock and subtotal.'],['Confirm the address','Collect the address and ask the customer to approve it.'],['Create the draft','Save the unconfirmed order and its items.','fastapi'],['Review the summary','Repeat items, quantities, address and total.'],['Confirm and recheck','Check the confirmation flag and current stock.'],['Save the order','Reduce stock and mark the order confirmed.']
],'Prompts ask for approval. Services check model-supplied confirmation flags and business data.',
'The order flow retrieves actual menu data and checks stock. The assistant collects and repeats the delivery address. A draft requires a confirmed-address flag. The assistant then repeats the order summary and asks for final approval. On confirmation, the service rechecks availability, reduces stock and updates the order. These flags come from model tool arguments. The source does not demonstrate an independent consent token or atomic, idempotent stock updates.',
'backend/app/services/order_service.py; backend/app/services/chat_service.py');
steps(detailed,'Table reservation confirmation','The backend chooses a suitable table after final confirmation.',[
 ['Collect the details','Date, time, party size, customer name and phone.'],['Check availability','Find sufficient capacity with no overlapping two-hour booking.'],['Save a draft','Keep the collected details as an unconfirmed reservation.','fastapi'],['Review the booking','Repeat the reservation summary and ask for approval.'],['Recheck the tables','Check the confirmation flag and current availability.'],['Assign and confirm','Choose an available table and save the confirmed booking.']
],'A draft does not reserve a table. Availability is checked again at confirmation.',
'The reservation service uses party size and two-hour booking windows to find suitable tables. It saves an unconfirmed draft from the collected details. The assistant asks the customer to approve the summary. On confirmation, the backend checks table availability again, assigns a suitable table and saves the confirmed state. The code does not establish race-free allocation under concurrent requests.',
'backend/app/services/reservation_service.py');
steps(detailed,'Planned SageMaker demand forecasting','Proposed workflow. The current recommendations screen contains static demo values.',[
 ['Prepare history','Aggregate historical demand by day and menu category.'],['Create the dataset','Prepare time series and store training data in S3.','s3'],['Train and evaluate','Train DeepAR and evaluate forecast quality.','sagemaker'],['Run inference','Generate seven-day category forecasts and quantile ranges.','sagemaker'],['Apply business rules','Derive preparation and inventory recommendations.','fastapi'],['Show recommendations','Serve forecast results to the admin dashboard.','next']
],'Planned throughout. Hourly staffing decisions require finer-grained data and additional rules.',
'The proposed forecasting feature is independent of the chat model. Historical category demand would become a time-series dataset in S3. SageMaker DeepAR would train on that data and produce a seven-day forecast with prediction quantiles. A backend endpoint and business rules would turn predictions into dashboard recommendations. The current code has only a SageMaker Runtime client helper and a static demo page. Training, inference and dashboard integration are not connected. Daily category forecasts alone cannot identify the busiest hourly service window.',
'backend/app/aws/sagemaker_client.py; Frontend/app/(admin)/admin/recommendations/page.tsx',true);
{
let s=base(detailed,'Implementation status','The architecture distinguishes source-code integrations from planned work.',detailed.slides.items.length+1);
const rows=[['Implemented in source','Next.js, FastAPI, SQLite, Qdrant, Bedrock, Titan, S3, Textract, Chime, Transcribe and Polly.'],['Optional configuration','Bedrock Guardrails on chat requests when an ID and version are supplied.'],['Planned feature','SageMaker training and inference. The recommendations page uses demo values.'],['Client helpers only','CloudWatch Logs and Secrets Manager. No connected application use found.'],['Separate prototype','A stdio MCP adapter exposes services and uses a fixed demo user.']];
rows.forEach((r,i)=>{txt(s,r[0],65,335+i*116,520,60,32,i===2?c.purple:c.accent,true);txt(s,r[1],645,335+i*116,1185,94,30,c.ink);});txt(s,'Source-code review only. Live AWS operation and production hosting were not verified.',65,955,1750,55,28,c.muted);
let notes='The code includes the main AI, knowledge and voice integrations, but this presentation does not claim live AWS tests were run. Guardrails depend on configuration. Forecasting remains planned. CloudWatch and Secrets Manager appear only as client factories with no connected usage found in the scanned application. The separate MCP prototype is not part of the main Bedrock tool path. Local runtime configuration does not establish an AWS production hosting design.';s.speakerNotes.textFrame.setText(notes+'\n'+sources);script.push({title:'Implementation status',notes});}
await fs.mkdir(out+'/images',{recursive:true});
async function save(p,name){let candidate=build+'/'+name+'.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);console.log('exported '+name);await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:out+'/'+name+'.pptx',pythonExecutable:'/Users/mac/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','18288000,10287000','--validate-heading-fit'],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:build+'/'+name+'.validation.json'});for(let i=0;i<p.slides.items.length;i++){const blob=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(out+'/images/'+name+'-'+String(i+1).padStart(2,'0')+'.png',new Uint8Array(await blob.arrayBuffer()));}console.log('rendered '+name);}
await save(overview(),'CallDine-System-Architecture');
await save(detailed,'CallDine-Step-by-Step');
await fs.writeFile(out+'/Video-Speaker-Notes.md','# CallDine video speaker notes\n\n'+script.map((a,i)=>'## '+(i+1)+'. '+a.title+'\n\n'+(a.steps?a.steps.map((v,j)=>'### Step '+(j+1)+': '+v.label+'\n\n'+v.say).join('\n\n')+'\n\n### Narration context\n\n':'')+a.notes).join('\n\n')+'\n\n## Sources\n\n'+sources+'\n');
console.log('DONE '+detailed.slides.items.length+' walkthrough slides');
