"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Logo } from "@/components/ui/Logo";
import type { SessionRole } from "@/lib/types";
import styles from "./Auth.module.css";

type Mode = "login" | "register" | "forgot";
export function AuthPage({ role = "customer", mode = "login" }: { role?: SessionRole; mode?: Mode }) {
  const router = useRouter(), isAdmin = role === "admin", [error, setError] = useState(""), [loading, setLoading] = useState(false);
  const copy = mode === "register" ? { title: "Create your account", sub: "Order and book by voice at every CallDine restaurant.", cta: "Create account" } : mode === "forgot" ? { title: "Reset your password", sub: "We’ll send instructions to your email address.", cta: "Send reset link" } : isAdmin ? { title: "Restaurant Admin", sub: "Sign in to manage orders, reservations, and AI calls.", cta: "Sign in" } : { title: "Welcome back", sub: "Sign in to order, book a table, or talk to the assistant.", cta: "Sign in" };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (mode !== "login") { router.push("/login"); return } setLoading(true); const data = new FormData(event.currentTarget); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: data.get("email"), password: data.get("password"), role }) }); const result = await response.json(); setLoading(false); if (!response.ok) { setError(result.error); return } router.replace(result.redirect); router.refresh() }
  const email = isAdmin ? "admin@admin.com" : "custmer@custmer.com", password = "password";
  return <main className={styles.wrap}><div className={styles.formSide}><form className={styles.form} onSubmit={submit}><Logo />{mode === "login" && <div className={styles.mobileWave} aria-hidden="true">{Array.from({ length: 24 }, (_, i) => <i key={i} style={{ height: 12 + Math.sin(i * .8) * 9 + Math.abs(12 - i) * .25, animationDelay: `${i * 45}ms` }}/>)}</div>}<div className={styles.heading}><h1>{copy.title}</h1><p>{copy.sub}</p></div><div className={styles.fields}>{mode === "register" && <label className={styles.field}><span>Full name</span><input className={styles.input} name="name" defaultValue="Yassine" /></label>}<label className={styles.field}><span>Email</span><input className={styles.input} name="email" type="email" defaultValue={email} required /></label>{mode !== "forgot" && <label className={styles.field}><span>Password</span><input className={styles.input} name="password" type="password" defaultValue={password} required /></label>}</div>{error && <div className={styles.error}>{error}</div>}<button className={styles.submit} disabled={loading}>{loading ? "Signing in…" : copy.cta}</button><div className={styles.links}>{mode === "login" ? <><span>{isAdmin ? <Link href="/login">Customer sign-in</Link> : <Link href="/register">Create account</Link>}</span>{!isAdmin && <Link href="/forgot-password">Forgot password?</Link>}</> : <Link href="/login">← Back to sign in</Link>}</div>{!isAdmin && mode === "login" && <Link href="/admin/login" className="eyebrow"> </Link>}</form></div><aside className={styles.visual}><span className={styles.badge}>{isAdmin ? "RESTAURANT ADMIN · OSTERIA VENTO" : "CALLDINE FOR GUESTS"}</span><div className={styles.wave}>{Array.from({ length: 38 }, (_, i) => <i className={styles.bar} key={i} style={{ height: 18 + Math.sin(i * .7) * 14 + Math.abs(19 - i) * .4, animationDelay: `${i * 35}ms` }} />)}</div><div className={styles.quote}><strong>{isAdmin ? "Every call, order, and AI decision in one operational view." : "Talk the way you would to a waiter. The assistant does the rest."}</strong>{isAdmin && <span>32 AI calls handled today without staff handover</span>}</div></aside></main>
}
